// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADcSwvj5j3681VeT-LWvxsN1q4CXFF9Ck',
    appId: '1:35989941029:android:9c6ab3926c439bdcdb48cc',
    messagingSenderId: '35989941029',
    projectId: 'njadia-15ffd',
    storageBucket: 'njadia-15ffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS6BsNSaFbpNsLEBUYM5tcQjPaGHhRTyE',
    appId: '1:35989941029:ios:ac2d907685b459d6db48cc',
    messagingSenderId: '35989941029',
    projectId: 'njadia-15ffd',
    storageBucket: 'njadia-15ffd.appspot.com',
    androidClientId: '35989941029-82rhvv0qccq7kbun5g834f367kq0pk3f.apps.googleusercontent.com',
    iosClientId: '35989941029-2g4knr16679lmm159m4qnhbqe41ibr66.apps.googleusercontent.com',
    iosBundleId: 'com.example.njadia',
  );
}
